### ISSUE TITLE
MongoDB respaldo para dummy

### ISSUE THREAD

**Issue by isayas** [PDNMX/dummy_api#3]
@BenitoPerdomo  Hola, cómo se puede obtener la BD en Mongo que alimenta la API dummy
ya tengo el servicio activo pero sin información en la BD.

**Comment by BenitoPerdomo** [comment]
@isayas : Buen día te comento que en estos días vamos a agregar un json con datos que puedas agregar en tu base de datos para que los puedas probar

**Comment by BenitoPerdomo** [comment]
@isayas hemos actualizado el proyecto [data_generator](https://github.com/PDNMX/data_generator) para que lo puedas usar para poblar tu base de datos de declaraciones.
